artel/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve

admin.autodiscover()

urlpatterns = [
    url(r'^sitemap\.xml$', sitemap,
        {'sitemaps': {'cmspages': CMSSitemap}}),
]

urlpatterns += i18n_patterns(
    url(r'^admin/', include(admin.site.urls)),  # NOQA
    url(r'^', include('cms.urls')),
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = [
        url(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ] + staticfiles_urlpatterns() + urlpatterns

custom_plugins/models.py
import os
from cms.models import CMSPlugin, Page
from cms.utils.compat.dj import python_2_unicode_compatible
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import ugettext_lazy as _

try:
    from cms.models import get_plugin_media_path
except ImportError:
    def get_plugin_media_path(instance, filename):
        """
        See cms.models.pluginmodel.get_plugin_media_path on django CMS 3.0.4+
        for information
        """
        return instance.get_media_path(filename)


class HideClass(models.Model):
    hide = models.BooleanField(_("hidden"), default=False, blank=True)

    class Meta:
        abstract = True


@python_2_unicode_compatible
class Intro(CMSPlugin, HideClass):
    """
    Plugin for about page.
    """
    major = models.CharField(_("major"), max_length=63,
                             help_text=_("Specifies text on top in tag <H2>."))
    image = models.ImageField(_("image"), upload_to=get_plugin_media_path,
                              blank=True)
    text = models.TextField(_("text"), blank=True,
                            help_text=_("Specifies main text with tags display"
                                        " filter '|safe'."))

    def __str__(self):
        return _(u"%s") % self.major


def technologies_logo_path(instance, filename):
    return 'logos/{}'.format(filename)


class Technology(models.Model):
    name = models.CharField(_('name'), max_length=255)
    logo = models.ImageField(
        _("logo"), upload_to=technologies_logo_path, blank=True)

    class Meta:
        verbose_name = "Technology"
        verbose_name_plural = "Technologies"

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Works(CMSPlugin, HideClass):
    """
    Plugin for wrok page.
    """
    major = models.CharField(_("major"), max_length=63,
                             help_text=_("Specifies text on top in tag <H2>."))
    total = models.CharField(_("total"), max_length=255, blank=True,
                             help_text=_("Specifies text after list of works in tag <p> style:italic."))

    def __str__(self):
        return _(u"%s") % self.major


@python_2_unicode_compatible
class Work(CMSPlugin, HideClass):
    """
    Plugin for each site definition.
    """
    title = models.CharField(_("title"), max_length=255, blank=True,)
    image = models.ImageField(_("image"), upload_to=get_plugin_media_path,
                              blank=True)
    link = models.CharField(_("link"), max_length=255, blank=True,
                            help_text=_("Specifies link where site is."))
    text = models.TextField(_("text"), blank=True,
                            help_text=_("Description for image"))
    technologies = models.ManyToManyField(Technology, blank=True)

    def __str__(self):
        return _(u"%s") % self.link


@python_2_unicode_compatible
class About(CMSPlugin, HideClass):
    """
    Plugin for wrok page.
    """
    major = models.CharField(_("major"), max_length=63,
                             help_text=_("Specifies text on top in tag <H2>."))
    description = models.TextField(_("description"), blank=True,
                                   help_text=_("Specifies text after major before mambers"))
    total = models.CharField(_("total"), max_length=255, blank=True,
                             help_text=_("Specifies text after list of members"))

    def __str__(self):
        return _(u"%s") % self.major


@python_2_unicode_compatible
class Member(CMSPlugin, HideClass):
    """
    Plugin for each site page.
    """
    image = models.ImageField(_("image"), upload_to=get_plugin_media_path,
                              blank=True)
    name = models.CharField(_("name"), max_length=255, blank=True,
                            help_text=_("Specifies link where site is."))
    text = models.TextField(_("text"), blank=True,
                            help_text=_("Description for image"))

    def __str__(self):
        return _(u"%s") % self.name


@python_2_unicode_compatible
class Contact(CMSPlugin, HideClass):
    """
    Plugin for each site page.
    """
    mail = models.CharField(_("mail"), max_length=63,
                            help_text=_("Specifies mail, which receive massage."))

    def __str__(self):
        return _(u"%s") % self.mail


class ContactModel(models.Model):
    """
    Model that collects massages.
    """
    mail = models.CharField(_("Address massage sent"), max_length=255)
    name = models.CharField(_("Name of subscriber"), max_length=64, blank=True)
    email = models.CharField(_("Callback address"), max_length=255, blank=True)
    message = models.TextField(_("Text in massage"))

    def __str__(self):
        return _(u"%s") % self.email


'''
@python_2_unicode_compatible
class Slide(CMSPlugin):
    """
    A Slide plugin that contains an image and some text.
    """

    image = models.ImageField(_("image"), upload_to=get_plugin_media_path)
    url = models.CharField(
        _("link"), max_length=255, blank=True, null=True,
        help_text=_("If present, clicking on image will take user to link."))

    page_link = models.ForeignKey(
        Page, verbose_name=_("page"), null=True,
        limit_choices_to={'publisher_is_draft': True}, blank=True,
        help_text=_("If present, clicking on image will take user to "
                    "specified page."))

    caption = models.TextField(
        _("caption"), max_length=255, blank=True, null=True,
        help_text=_("Specifies text that occurs on the slide."))

    def __str__(self):
        if self.caption:
            return self.caption[:40]
        elif self.image:
            # added if, because it raised attribute error when file wasn't
            # defined.
            try:
                return u"%s" % os.path.basename(self.image.name)
            except AttributeError:
                pass
        return u"<empty>"

    def clean(self):
        if self.url and self.page_link:
            raise ValidationError(
                _("You can enter a Link or a Page, but not both."))


@python_2_unicode_compatible
class Slider(CMSPlugin):
    """
    Plugin that can only contain Slides.
    """

    def __str__(self):
        return _(u"%s Images") % self.cmsplugin_set.all().count()
'''

custom_plugins/forms.py
from django import forms
from .models import ContactModel


class ContactForm(forms.ModelForm):

    class Meta:
        model = ContactModel
        fields = ('name', 'email', 'message', )

custom_plugins/views.py
from django.shortcuts import render

# Create your views here.

artel/templates/base.html
{% load cms_tags menu_tags sekizai_tags %}
{% load static %}
<!DOCTYPE HTML>

<!--
    Dimension by HTML5 UP
    html5up.net | @ajlkn
    Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
    <head>
        <title>{% block title %}Artel7{% endblock title %}</title>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
<!-- Yandex.Metrika counter --> <script type="text/javascript" > (function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter38851015 = new Ya.Metrika({ id:38851015, clickmap:true, trackLinks:true, accurateTrackBounce:true, webvisor:true, trackHash:true }); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = "https://cdn.jsdelivr.net/npm/yandex-metrica-watch/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks"); </script> <noscript><div><img src="https://mc.yandex.ru/watch/38851015" style="position:absolute; left:-9999px;" alt="" /></div></noscript> <!-- /Yandex.Metrika counter -->


        <link rel="stylesheet" href="{% static 'css/main.css' %}" />
        <!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
        <noscript><link rel="stylesheet" href="{% static 'css/noscript.css' %}" /></noscript>
        <link rel="stylesheet" href="{% static 'css/custom.css' %}" />
        {% render_block "css" %}
    </head>
    {% comment %}  
    <body>
        {% cms_toolbar %}
        <div class="container">
            <ul class="nav">
                {% show_menu 0 100 100 100 %}
            </ul>
            {% block content %}{% endblock content %}
        </div>
        {% render_block "js" %}
    </body>
    {% endcomment %}
    <body>
    {% cms_toolbar %}
        <!-- Wrapper -->
            <div id="wrapper">

                <!-- Header -->
                    <header id="header">
                        <div class="logo">
                            {# <span class="icon fa-diamond"></span> #}
                            <img class='icon' height='50px' src="{% static 'images/logo.png' %}"/>
                        </div>
                        <div class="content">
                            <div class="inner">
                                <h1>Artel Seven</h1>
                                <p><!--[-->Python developer team. <!--]--><br />
                                <!--[-->Basically we specialized on frameworks like Django and Django based django cms, Wagtail, django REST.<!--]--></p>
                            </div>
                        </div>
                        <nav>
                            <ul>
                                <li><a href="#intro">Intro</a></li>
                                <li><a href="#work">Work</a></li>
                                <li><a href="#about">About</a></li>
                                <li><a href="#contact">Contact</a></li>
                                <!--<li><a href="#elements">Elements</a></li>-->
                            </ul>
                        </nav>
                    </header>

                <!-- Main -->
                    <div id="main">
                        {% block content %}
                        {% endblock content %}
                    </div>

                <!-- Footer -->
                    <footer id="footer">
                        <p class="copyright">&copy; Artel7. Design: <a href="https://html5up.net">HTML5 UP</a>.</p>
			<p class="copyright">Photo:<a href="https://www.flickr.com/photos/125167502@N02/">by markus spiske </a></p>
                    </footer>

            </div>

        <!-- BG -->
            <div id="bg"></div>

        <!-- Scripts -->
            <script src="{% static 'js/jquery.min.js' %}"></script>
            <script src="{% static 'js/skel.min.js' %}"></script>
            <script src="{% static 'js/util.js' %}"></script>
            <script src="{% static 'js/main.js' %}"></script>
            <script src="{% static 'js/jquery.lazyloadxt.min.js' %}"></script>
        {% render_block "js" %}

<script type="text/javascript">
    $('img').lazyLoadXT();
</script>
    </body>
</html>

{% comment %}  
<html>
    <head>
        <title>{% block title %}This is my new project home page{% endblock title %}</title>
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <style type="text/css">
            .nav {
                padding-left: 0;
            }
            .nav li {
                display: inline;
                list-style-type: none;
                padding-right: 20px;
            }
            .container {
                width: 940px;
                margin: 0 auto
            }
            .content {
                float: left;
                width: 80%;
            }
            .sidebar {
                float: left;
                width: 20%;
            }
        </style>
        {% render_block "css" %}
    </head>
    <body>
        {% cms_toolbar %}
        <div class="container">
            <ul class="nav">
                {% show_menu 0 100 100 100 %}
            </ul>
            {% block content %}{% endblock content %}
        </div>
        {% render_block "js" %}
    </body>
<script id="fragment" type="x-shader/x-fragment">

#define RAIN_SPEED 1.75 // Speed of rain droplets
#define DROP_SIZE  3.0  // Higher value lowers, the size of individual droplets

float rand(vec2 co){
    return fract(sin(dot(co.xy ,vec2(12.9898,78.233))) * 43758.5453);
}

float rchar(vec2 outer, vec2 inner, float globalTime) {
	//return float(rand(floor(inner * 2.0) + outer) > 0.9);
	
	vec2 seed = floor(inner * 4.0) + outer.y;
	if (rand(vec2(outer.y, 23.0)) > 0.98) {
		seed += floor((globalTime + rand(vec2(outer.y, 49.0))) * 3.0);
	}
	
	return float(rand(seed) > 0.5);
}

void mainImage( out vec4 fragColor, in vec2 fragCoord ) {

	vec2 position = fragCoord.xy / iResolution.xy;
	vec2 uv = vec2(position.x, position.y);
    position.x /= iResolution.x / iResolution.y;
	float globalTime = iGlobalTime * RAIN_SPEED;
	
	float scaledown = DROP_SIZE;
	float rx = fragCoord.x / (40.0 * scaledown);
	float mx = 40.0*scaledown*fract(position.x * 30.0 * scaledown);
	vec4 result;
	
	if (mx > 12.0 * scaledown) {
		result = vec4(0.0);
	} else 
	{
        float x = floor(rx);
		float r1x = floor(fragCoord.x / (15.0));
		

		float ry = position.y*600.0 + rand(vec2(x, x * 3.0)) * 100000.0 + globalTime* rand(vec2(r1x, 23.0)) * 120.0;
		float my = mod(ry, 15.0);
		if (my > 12.0 * scaledown) {
			result = vec4(0.0);
		} else {
		
			float y = floor(ry / 15.0);
			
			float b = rchar(vec2(rx, floor((ry) / 15.0)), vec2(mx, my) / 12.0, globalTime);
			float col = max(mod(-y, 24.0) - 4.0, 0.0) / 20.0;
			vec3 c = col < 0.8 ? vec3(0.0, col / 0.8, 0.0) : mix(vec3(0.0, 1.0, 0.0), vec3(1.0), (col - 0.8) / 0.2);
			
			result = vec4(c * b, 1.0)  ;
		}
	}
	
	position.x += 0.05;

	scaledown = DROP_SIZE;
	rx = fragCoord.x / (40.0 * scaledown);
	mx = 40.0*scaledown*fract(position.x * 30.0 * scaledown);
	
	if (mx > 12.0 * scaledown) {
		result += vec4(0.0);
	} else 
	{
        float x = floor(rx);
		float r1x = floor(fragCoord.x / (12.0));
		

		float ry = position.y*700.0 + rand(vec2(x, x * 3.0)) * 100000.0 + globalTime* rand(vec2(r1x, 23.0)) * 120.0;
		float my = mod(ry, 15.0);
		if (my > 12.0 * scaledown) {
			result += vec4(0.0);
		} else {
		
			float y = floor(ry / 15.0);
			
			float b = rchar(vec2(rx, floor((ry) / 15.0)), vec2(mx, my) / 12.0, globalTime);
			float col = max(mod(-y, 24.0) - 4.0, 0.0) / 20.0;
			vec3 c = col < 0.8 ? vec3(0.0, col / 0.8, 0.0) : mix(vec3(0.0, 1.0, 0.0), vec3(1.0), (col - 0.8) / 0.2);
			
			result += vec4(c * b, 1.0)  ;
		}
	}
	
	result = result * length(texture(iChannel0,uv).rgb) + 0.22 * vec4(0.,texture(iChannel0,uv).g,0.,1.);
	if(result.b < 0.5)
	result.b = result.g * 0.5 ;
	fragColor = result;
}
</script>

</html>
{% endcomment %}

artel/templates/fullwidth.html
{% extends "base.html" %}
{% load cms_tags %}

{% block title %}{% page_attribute "page_title" %}{% endblock title %}

{% block content %}
	{% placeholder "content" %}
{% endblock content %}

artel/templates/sidebar_left.html
{% extends "base.html" %}
{% load cms_tags %}

{% block title %}{% page_attribute "page_title" %}{% endblock title %}

{% block content %}
    <div class="sidebar">
        {% placeholder "sidebar" %}
    </div>
    <div class="content">
        {% placeholder "content" %}
    </div>
{% endblock content %}

artel/templates/sidebar_right.html
{% extends "base.html" %}
{% load cms_tags %}

{% block title %}{% page_attribute "page_title" %}{% endblock title %}

{% block content %}
    <div class="content">
        {% placeholder "content" %}
    </div>
    <div class="sidebar">
        {% placeholder "sidebar" %}
    </div>
{% endblock content %}

custom_plugins/templates/custom_plugins/about.html
{% load sekizai_tags cms_tags %}
{% load static %}
{% if not instance.hide %}
<!-- About -->
    <article id="about">
        <h2 class="major">{{ instance.major }}</h2>
        <p>{{ instance.description|safe }}</p>
        {% for plugin in instance.child_plugin_instances %}
            {% if not  plugin.hide %}
                {% render_plugin plugin %}
            {% endif %}
        {% endfor %}
        <p style="font-style:italic;">{{ instance.total }}</p>
    </article>
{% endif %}

custom_plugins/templates/custom_plugins/contact.html
<!-- Contact -->
    <article id="contact">
        <h2 class="major">Contact</h2>
        <form method="post" action="#">
        {% csrf_token %}
            <div class="field half first">
                <label for="name">Name</label>
                <input type="text" id="id_name" maxlength="64" name="name"  />
            </div>
            <div class="field half">
                <label for="email">Email</label>
                <input id="id_email" maxlength="255" name="email" type="text" />
            </div>
            <div class="field">
                <label for="message">Message</label>
                <textarea id="id_message" name="message" rows="4"></textarea>
            </div>
            <ul class="actions">
                <li><input type="submit" value="Send Message" class="special" /></li>
                <li><input type="reset" value="Reset" /></li>
            </ul>
        </form>
        {% comment %}  
        <ul class="icons">
            <li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
            <li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
            <li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
            <li><a href="#" class="icon fa-github"><span class="label">GitHub</span></a></li>
        </ul>
        {% endcomment %}
    </article>

custom_plugins/templates/custom_plugins/intro.html
{% if not instance.hide %}
<!-- Intro -->
    <article id="intro">
        <h2 class="major">{{ instance.major }}</h2>
        {# {% thumbnail instance.image "200x200"  as thumb %} {{ thumb.url }}#}
        {% if instance.image %}
            <span class="image main"><img data-src="{{ instance.image.url }}" alt="" /></span>
        {% endif %}
        {{ instance.text|safe }}
    </article>
{% endif %}

custom_plugins/templates/custom_plugins/member.html
<div class='half'>
    {# {% thumbnail instance.image "200x200"  as thumb %} {{ thumb.url }}#}
    {% if instance.image %}
        <span class="image main"><img data-src="{{ instance.image.url }}" alt="" /></span>
    {% endif %}
    <h3>{{ instance.name }}</h3>
    <p>{{ instance.text }}</p>
</div>

custom_plugins/templates/custom_plugins/slide_example.html
{% load thumbnail %}

<li class="slideshow-slide">
  {% thumbnail instance.image "1920x480" crop="center" as thumb %}
  <img data-src="{{ thumb.url }}" width="1920" height="480" alt="{{ instance.alt }}"{% if instance.longdesc %} title="{{ instance.longdesc }}"{% endif %} />
  {% endthumbnail %}
</li>

custom_plugins/templates/custom_plugins/slider_example.html
{% load sekizai_tags cms_tags %}
<div class="slider">
	<ul class="slides">
   {% autoescape off %}
   {% for plugin in instance.child_plugin_instances %}
   {% render_plugin plugin %}
        {% comment %}
		<li>
			<figure>
				{% if image.url %}
                {{ image }}
                    <a href="{{ image.url }}"><img data-src="{{ PUBLIC_URL }}{% thumbnail image.image 1170x500 upscale crop %}" alt="{{ image.name }}" /></a>

                    <img data-src="{{ PUBLIC_URL }}{% thumbnail image.image 1170x500 upscale crop %}" alt="{{ image.name }}" />
                {% endif %}
			</figure>
		</li>
    {% endcomment %}
    {% endfor %}
    {% endautoescape %}
  </ul>
</div>

{% addtoblock "css" %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flexslider/2.6.0/flexslider.min.css" />
{% endaddtoblock %}

{% addtoblock "js" %}
<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/flexslider/2.2.2/jquery.flexslider-min.js"></script>
<script type="text/javascript">
  $(document).ready(function() {
    $('.slider').flexslider({
      animation: "slide"
      ,pauseOnAction: false
      ,pauseOnHover: true
      ,controlNav: false
    });
  });
</script>
{% endaddtoblock %}

custom_plugins/templates/custom_plugins/work-detail.html
{% load thumbnail %}
     {# {% thumbnail instance.image "200x200"  as thumb %} {{ thumb.url }} #}
     {% if instance.title %}
         <h3 class="work_title">{{ instance.title }}</h3>
     {% endif %}
     {% if instance.image %}
    <a href="{{ instance.link }}" target="_blank"><span class="image main"><img data-src="{{ instance.image.url }}" alt="" /></span></a>
    {% endif %}
    {% for technology in instance.technologies.all %}
        {% if technology.logo %}
             <img class='technology_logo' src="{% thumbnail technology.logo '100x50' %}"/>
        {% else %}
            <span class="label label-default">{{ technology.name }}</span>
        {% endif %}
    {% endfor %}
    <p>{{ instance.text }}</p>
 

custom_plugins/templates/custom_plugins/works.html
{% load sekizai_tags cms_tags %}
{% load static %}
{% if not instance.hide %}
<!-- Work -->
    <article id="work">
        <h2 class="major">>{{ instance.major }}</h2>
        {% for plugin in instance.child_plugin_instances %}
            {% if not  plugin.hide %}
                {% render_plugin plugin %}
            {% endif %}
        {% endfor %}
        <p style="font-style:italic;">{{ instance.total }}</p>
    </article>
{% endif %}